### PR TITLE
Bugfix / `hashcode`, `equals`, `toString` implementation

### LINKED ISSUE #4: [BUG] Models doesn't have `hashCode`, `equals`, `toString` implementation
**Describe the bug**
As title says, models doesn't have any implementation of `hashCode`, `equals`, `toString` which will may lead into usability problem.

---

**To Reproduce**
1. Create any model
2. Initialize model using `ConfigurationNode#get`
3. `System.out.println(yourModel);`
4. In console output you will see 'null', same behaviour for `equals`, `hashCode`

---

**Expected behavior**
`hashCode`, `equals` should be implemented correctly. When we'll call `model.equals(model)` it should return `true` 

---

**Code snipper or screenshot**
Model:
```java
@ConfigInterface
public interface SimpleModel {
  String text();
}
```
Loading and usage:
```java
public class Usage {
  public void usage(ConfigurationNode node) {
    SimpleModel model = node.get(SimpleModel.class);
    System.out.println(model); // null
    System.out.println(model.equals(model)); // false
    System.out.println(model.toString()); // null
    System.out.println(model.hashCode()); // 0
  }
}
```

### PR DESCRIPTION
**Pull request by bivashy**
## Pull Request Etiquette

- [x] I have checked the PRs for upcoming features/bug fixes.

### Changes

- [X] Internal code
- [X] API (affecting end-user code)
- [ ] Other: _

Closes Issue: #4 

## Description

This pull request creates implementation for `hashCode`, `equals`, `toString`, also provides way to override this methods using `hash`, `equalTo`, `stringify` methods. 

**Breaking changes** Replaced `Object` intermediate with `Map<String, Object>` in `ProxyMethodInvoker`

### CODE REVIEW

File: common/src/main/java/com/bivashy/configurate/objectmapping/common/meta/MethodInvokers.java [hunk 1]
```diff
@@ -13,7 +18,15 @@ private MethodInvokers() {
 
     public static ProxyMethodInvoker toStringInvoker() {
         return (proxy, method, args, intermediate) -> {
-            if (method.getName().equals("toString") && (args == null || args.length == 0)) {
+            if (!method.getName().equals("toString") || args != null && args.length != 0)
+                return null;
+            try {
+                Method stringifyMethod = findUnderlyingMethod(proxy, "stringify");
+                if (!stringifyMethod.isDefault())
+                    throw new IllegalStateException("Cannot call 'stringify' on '" + Arrays.toString(proxy.getClass().getInterfaces()) +
```
Comment (bivashy) [inline common/src/main/java/com/bivashy/configurate/objectmapping/common/meta/MethodInvokers.java]: [nitpick] I think this should be moved into `findUnderlyingMethod`

File: common/src/main/java/com/bivashy/configurate/objectmapping/common/meta/MethodInvokers.java [hunk 2]
```diff
@@ -25,8 +38,66 @@ public static ProxyMethodInvoker toStringInvoker() {
...
+    }
+
+    public static ProxyMethodInvoker hashCodeInvoker() {
+        return (proxy, method, args, intermediate) -> {
+            if (!method.getName().equals("hashCode") || args != null && args.length != 0)
+                return null;
+            try {
+                Method hashMethod = findUnderlyingMethod(proxy, "hash");
+                if (!hashMethod.isDefault())
+                    throw new IllegalStateException("Cannot call 'hash' on '" + Arrays.toString(proxy.getClass().getInterfaces()) +
```
Comment (bivashy) [inline common/src/main/java/com/bivashy/configurate/objectmapping/common/meta/MethodInvokers.java]: [nitpick] I think this should be moved into `findUnderlyingMethod`

File: common/src/main/java/com/bivashy/configurate/objectmapping/common/meta/MethodInvokers.java [hunk 3]
```diff
@@ -25,8 +38,66 @@ public static ProxyMethodInvoker toStringInvoker() {
...
 
+    public static ProxyMethodInvoker equalsInvoker() {
+        return (proxy, method, args, intermediate) -> {
+            if (!method.getName().equals("equals") || args == null || args.length != 1 || method.getParameterTypes()[0] != Object.class)
+                return null;
+            Object object = args[0];
+            try {
+                Method equalToMethod = findUnderlyingMethod(proxy, "equalTo", Object.class);
+                if (!equalToMethod.isDefault())
+                    throw new IllegalStateException("Cannot call 'equalTo' on '" + Arrays.toString(proxy.getClass().getInterfaces()) +
```
Comment (bivashy) [inline common/src/main/java/com/bivashy/configurate/objectmapping/common/meta/MethodInvokers.java]: [nitpick] I think this should be moved into `findUnderlyingMethod`
